version: '3.4'

services:
  mykaryawanportal:
    image: mykaryawan-portal
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
